# Generated by Django 5.1.1 on 2024-10-10 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('tipoUsuario', models.CharField(max_length=50)),
                ('idAdministrador', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('tipoUsuario', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('tipoUsuario', models.CharField(max_length=50)),
                ('idProfesor', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCurso', models.CharField(max_length=50, unique=True)),
                ('nombreCurso', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('estudiantes', models.ManyToManyField(related_name='cursos', to='portal.estudiante')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCalificacion', models.CharField(max_length=50, unique=True)),
                ('valor', models.FloatField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEvaluacion', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('calificaciones', models.ManyToManyField(related_name='evaluaciones', to='portal.calificacion')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.curso')),
            ],
        ),
        migrations.AddField(
            model_name='calificacion',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.evaluacion'),
        ),
    ]
